# This workflow will install Python dependencies, run tests, and upload test coverage
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: run-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7"]
        pytorch-version: ["1.0", "1.1"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install torch==${{ matrix.pytorch-version }}
        python -m pip install --upgrade numpy
        python -m pip install -r requirements-test.txt
        python -m pip install -e .
    - name: Test with pytest
      run: pytest
    - name: Upload coverage data to coveralls.io
      run: |
        python -m pip install coveralls
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ success() }}$
